# Copyright (c) 2026-present The Bitcoin Core developers
# Distributed under the MIT software license, see the accompanying
# file COPYING or http://www.opensource.org/licenses/mit-license.php.

if(NOT DEFINED SOURCE_DIR)
  message(FATAL_ERROR "SOURCE_DIR is required")
endif()

include("${SOURCE_DIR}/cmake/BitcoinApiManifest.cmake")

function(require_file relative_path)
  if(NOT EXISTS "${SOURCE_DIR}/${relative_path}")
    message(FATAL_ERROR "API manifest expects ${relative_path} to exist")
  endif()
endfunction()

function(forbid_file relative_path)
  if(EXISTS "${SOURCE_DIR}/${relative_path}")
    message(FATAL_ERROR "API manifest forbids source-tree documentation path: ${relative_path}")
  endif()
endfunction()

function(require_text relative_path needle)
  file(READ "${SOURCE_DIR}/${relative_path}" contents)
  string(FIND "${contents}" "${needle}" match_index)
  if(match_index EQUAL -1)
    message(FATAL_ERROR "${relative_path} is missing required API-manifest text: ${needle}")
  endif()
endfunction()

function(forbid_text relative_path needle)
  file(READ "${SOURCE_DIR}/${relative_path}" contents)
  string(FIND "${contents}" "${needle}" match_index)
  if(NOT match_index EQUAL -1)
    message(FATAL_ERROR "${relative_path} contains forbidden API-manifest text: ${needle}")
  endif()
endfunction()

function(forbid_cmake_target relative_path target_name)
  file(READ "${SOURCE_DIR}/${relative_path}" contents)
  string(REGEX MATCH "add_(library|executable)\\(${target_name}([ \t\r\n\\)]|$)" target_match "${contents}")
  if(target_match)
    message(FATAL_ERROR "${relative_path} declares forbidden API-manifest target: ${target_name}")
  endif()
endfunction()

function(forbid_cmake_target_link relative_path target_name dependency_name)
  file(READ "${SOURCE_DIR}/${relative_path}" contents)
  string(REGEX MATCHALL "target_link_libraries\\([ \t\r\n]*${target_name}[^\\)]*\\)" link_blocks "${contents}")
  foreach(link_block IN LISTS link_blocks)
    string(REGEX MATCH "(^|[ \t\r\n])${dependency_name}([ \t\r\n\\)]|$)" dependency_match "${link_block}")
    if(dependency_match)
      message(FATAL_ERROR
        "${relative_path} links ${target_name} to forbidden API-manifest dependency: ${dependency_name}")
    endif()
  endforeach()
endfunction()

function(record_api_manifest_blocker blocker)
  set_property(GLOBAL APPEND PROPERTY API_MANIFEST_BLOCKERS "${blocker}")
endfunction()

function(require_release_text relative_path needle blocker)
  file(READ "${SOURCE_DIR}/${relative_path}" contents)
  string(FIND "${contents}" "${needle}" match_index)
  if(match_index EQUAL -1)
    record_api_manifest_blocker("${blocker}")
  endif()
endfunction()

function(fail_on_api_manifest_blockers)
  get_property(blockers GLOBAL PROPERTY API_MANIFEST_BLOCKERS)
  if(blockers)
    list(REMOVE_DUPLICATES blockers)
    list(JOIN blockers "\n  " blocker_text)
    message(FATAL_ERROR "API manifest release gates are not satisfied:\n  ${blocker_text}")
  endif()
endfunction()

function(require_list_contains list_name item)
  list(FIND ${list_name} "${item}" item_index)
  if(item_index EQUAL -1)
    message(FATAL_ERROR "${list_name} does not contain ${item}")
  endif()
endfunction()

function(require_manifested_cpp_target target_name)
  list(FIND BITCOIN_API_SHIPPED_REQUIRED_TARGETS "${target_name}" shipped_required_index)
  list(FIND BITCOIN_API_SHIPPED_OPTIONAL_TARGETS "${target_name}" shipped_optional_index)
  list(FIND BITCOIN_API_EXPERIMENTAL_TARGETS "${target_name}" experimental_index)
  if(shipped_required_index EQUAL -1
      AND shipped_optional_index EQUAL -1
      AND experimental_index EQUAL -1)
    message(FATAL_ERROR "C ABI concept maps to unmanifested C++ target: ${target_name}")
  endif()
endfunction()

function(require_c_abi_target target_name)
  if(target_name STREQUAL "bitcoinkernel")
    require_text("src/kernel/CMakeLists.txt" "add_library(bitcoinkernel")
    return()
  endif()

  message(FATAL_ERROR "Unknown C ABI manifest target: ${target_name}")
endfunction()

function(require_c_abi_release_blockers_resolved)
  list(FIND BITCOIN_API_SHIPPED_REQUIRED_TARGETS "bitcoinkernel" legacy_cpp_shipped_index)
  list(FIND BITCOIN_API_SHIPPED_OPTIONAL_TARGETS "bitcoinkernel" legacy_cpp_optional_index)
  if(NOT legacy_cpp_shipped_index EQUAL -1 OR NOT legacy_cpp_optional_index EQUAL -1)
    record_api_manifest_blocker(
      "bitcoinkernel is a C ABI target, not a C++ API target; move it out of BITCOIN_API_SHIPPED_* and satisfy BITCOIN_C_ABI_SHIPPED_TARGETS gates before release.")
  endif()

  foreach(target IN LISTS BITCOIN_C_ABI_SHIPPED_TARGETS)
    require_c_abi_target("${target}")
    if(target STREQUAL "bitcoinkernel")
      set(blocking_text_found)
      file(READ "${SOURCE_DIR}/src/kernel/bitcoinkernel.h" bitcoinkernel_header)
      foreach(needle IN LISTS BITCOIN_C_ABI_RELEASE_BLOCKING_TEXT)
        string(FIND "${bitcoinkernel_header}" "${needle}" match_index)
        if(NOT match_index EQUAL -1)
          list(APPEND blocking_text_found "${needle}")
        endif()
      endforeach()
      if(blocking_text_found)
        list(REMOVE_DUPLICATES blocking_text_found)
        list(JOIN blocking_text_found "\n  " blocker_text)
        record_api_manifest_blocker(
          "bitcoinkernel cannot be a shipped C ABI target while release-blocking ABI text remains:\n  ${blocker_text}\n  Split pure validation C ABI to bitcoin_validation_c or remove it, and add ABI version/size/symbol gates before promotion.")
      endif()
    endif()
  endforeach()
endfunction()

function(require_header_allowlist_exact list_name glob_pattern)
  set(expected ${${list_name}})
  file(GLOB actual RELATIVE "${SOURCE_DIR}/src" "${SOURCE_DIR}/src/${glob_pattern}")
  list(SORT expected)
  list(SORT actual)
  if(NOT "${actual}" STREQUAL "${expected}")
    message(FATAL_ERROR
      "${list_name} does not match ${glob_pattern}\n"
      "Expected: ${expected}\n"
      "Actual: ${actual}")
  endif()
endfunction()

function(require_manifest_headers_exist list_name)
  foreach(header IN LISTS ${list_name})
    require_file("src/${header}")
  endforeach()
endfunction()

function(require_no_release_header_blockers list_name)
  set(blockers)
  foreach(header IN LISTS ${list_name})
    foreach(needle IN LISTS BITCOIN_VALIDATION_PUBLIC_HEADER_FORBIDDEN_TEXT)
      file(READ "${SOURCE_DIR}/src/${header}" contents)
      string(FIND "${contents}" "${needle}" match_index)
      if(NOT match_index EQUAL -1)
        list(APPEND blockers "${header}: ${needle}")
      endif()
    endforeach()
    foreach(needle IN LISTS BITCOIN_VALIDATION_RELEASE_PENDING_FORBIDDEN_TEXT)
      file(READ "${SOURCE_DIR}/src/${header}" contents)
      string(FIND "${contents}" "${needle}" match_index)
      if(NOT match_index EQUAL -1)
        list(APPEND blockers "${header}: ${needle}")
      endif()
    endforeach()
  endforeach()

  if(blockers)
    list(REMOVE_DUPLICATES blockers)
    list(JOIN blockers "\n  " blocker_text)
    string(CONCAT header_blocker
      "Validation release headers still expose forbidden public-surface text:\n"
      "  ${blocker_text}\n"
      "  Move implementation helpers behind non-installed headers or promote them with release contracts before shipping bitcoin_validation.")
    record_api_manifest_blocker("${header_blocker}")
  endif()
endfunction()

function(require_c_abi_cpp_concept_rule rule)
  string(REPLACE "|" ";" fields "${rule}")
  list(LENGTH fields field_count)
  if(NOT field_count EQUAL 4)
    message(FATAL_ERROR "Malformed active C ABI concept rule: ${rule}")
  endif()

  list(GET fields 0 c_symbol)
  list(GET fields 1 cpp_target)
  list(GET fields 2 cpp_header)
  list(GET fields 3 cpp_needle)

  require_text("src/kernel/bitcoinkernel.h" "${c_symbol}")
  require_manifested_cpp_target("${cpp_target}")
  require_text("src/${cpp_header}" "${cpp_needle}")
endfunction()

function(require_pending_c_abi_cpp_concept_rule rule)
  string(REPLACE "|" ";" fields "${rule}")
  list(LENGTH fields field_count)
  if(NOT field_count EQUAL 3)
    message(FATAL_ERROR "Malformed pending C ABI concept rule: ${rule}")
  endif()

  list(GET fields 0 c_symbol)
  list(GET fields 1 cpp_target)
  require_text("src/kernel/bitcoinkernel.h" "${c_symbol}")
  require_list_contains(BITCOIN_API_PENDING_REQUIRED_TARGETS "${cpp_target}")
endfunction()

function(require_c_abi_functions_manifested)
  file(READ "${SOURCE_DIR}/src/kernel/bitcoinkernel.h" header_contents)
  string(REGEX MATCHALL "BITCOINKERNEL_API[^;\n]*btck_[A-Za-z0-9_]+\\(" declarations "${header_contents}")
  foreach(declaration IN LISTS declarations)
    string(REGEX REPLACE ".*(btck_[A-Za-z0-9_]+)\\(.*" "\\1" function_name "${declaration}")
    set(function_is_manifested FALSE)
    foreach(prefix IN LISTS BITCOIN_C_ABI_ALLOWED_FUNCTION_PREFIXES)
      string(FIND "${function_name}" "${prefix}" prefix_index)
      if(prefix_index EQUAL 0)
        set(function_is_manifested TRUE)
      endif()
    endforeach()

    if(NOT function_is_manifested)
      message(FATAL_ERROR
        "C ABI function ${function_name} is not covered by "
        "BITCOIN_C_ABI_ALLOWED_FUNCTION_PREFIXES in BitcoinApiManifest.cmake")
    endif()
  endforeach()
endfunction()

foreach(target IN LISTS BITCOIN_API_SHIPPED_REQUIRED_TARGETS)
  if(target STREQUAL "bitcoinkernel")
    require_text("src/kernel/CMakeLists.txt" "add_library(bitcoinkernel")
  else()
    require_text("src/CMakeLists.txt" "add_library(${target} STATIC EXCLUDE_FROM_ALL")
  endif()
endforeach()

foreach(target IN LISTS BITCOIN_API_SHIPPED_OPTIONAL_TARGETS)
  require_text("src/CMakeLists.txt" "add_library(${target} STATIC EXCLUDE_FROM_ALL")
endforeach()

foreach(target IN LISTS BITCOIN_API_EXPERIMENTAL_TARGETS)
  require_text("src/CMakeLists.txt" "add_library(${target} STATIC EXCLUDE_FROM_ALL")
  forbid_text("src/CMakeLists.txt" "install(TARGETS ${target}")
  forbid_text("src/CMakeLists.txt" " ${target}\n  EXPORT BitcoinValidationTargets")
endforeach()

foreach(target IN LISTS BITCOIN_C_ABI_EXPERIMENTAL_TARGETS)
  require_c_abi_target("${target}")
endforeach()

foreach(target IN LISTS
    BITCOIN_API_PENDING_REQUIRED_TARGETS
    BITCOIN_API_NOT_SHIPPING_OPTIONAL_TARGETS
    BITCOIN_C_ABI_NOT_SHIPPING_OPTIONAL_TARGETS)
  forbid_cmake_target("src/CMakeLists.txt" "${target}")
  forbid_cmake_target("src/kernel/CMakeLists.txt" "${target}")
endforeach()

require_c_abi_release_blockers_resolved()

forbid_text("src/CMakeLists.txt" "bitcoin_validation_library")
forbid_text("src/test/CMakeLists.txt" "bitcoin_validation_library")
require_text("src/CMakeLists.txt" "install(TARGETS bitcoin_protocol bitcoin_validation")
require_text("src/CMakeLists.txt" "EXPORT BitcoinValidationTargets")
require_text("src/CMakeLists.txt" "install(EXPORT BitcoinValidationTargets")
forbid_text("src/CMakeLists.txt" "install(TARGETS bitcoin_protocol bitcoin_validation bitcoin_validation_script_engine_objects")
forbid_text("src/CMakeLists.txt" "install(TARGETS bitcoin_protocol bitcoin_validation bitcoin_validation_private_script_engine")
forbid_text("src/CMakeLists.txt" "install(TARGETS bitcoin_protocol bitcoin_validation bitcoin_kernel")
require_text("src/CMakeLists.txt" "BitcoinValidationConfig.cmake")
require_text("cmake/BitcoinValidationConfig.cmake.in" "find_dependency(libsecp256k1 CONFIG REQUIRED)")
require_text("src/CMakeLists.txt" "crypto/sha256.cpp")
require_text("src/CMakeLists.txt" "crypto/ripemd160.cpp")
require_text("src/CMakeLists.txt" "add_library(bitcoin_validation_script_engine_objects OBJECT")
require_text("src/CMakeLists.txt" "$<TARGET_OBJECTS:bitcoin_validation_script_engine_objects>")
forbid_text("src/CMakeLists.txt" "add_library(bitcoin_validation_private_script_engine")
forbid_text("src/CMakeLists.txt" "bitcoin_validation_private_script_engine")
forbid_cmake_target_link("src/CMakeLists.txt" "bitcoin_protocol" "bitcoin_crypto")
require_text("src/CMakeLists.txt" "$<INSTALL_INTERFACE:")

require_header_allowlist_exact(BITCOIN_PROTOCOL_PUBLIC_HEADERS "bitcoin/protocol/*.h")
require_header_allowlist_exact(BITCOIN_VALIDATION_PUBLIC_HEADERS "bitcoin/validation/*.h")
require_header_allowlist_exact(BITCOIN_CHAIN_GRAPH_PUBLIC_HEADERS "bitcoin/chain_graph/*.h")
require_manifest_headers_exist(BITCOIN_PROTOCOL_PUBLIC_HEADERS)
require_manifest_headers_exist(BITCOIN_VALIDATION_PUBLIC_HEADERS)
require_manifest_headers_exist(BITCOIN_CHAIN_GRAPH_PUBLIC_HEADERS)
require_manifest_headers_exist(BITCOIN_BITCOINKERNEL_PUBLIC_HEADERS)
forbid_file("doc")

require_no_release_header_blockers(BITCOIN_VALIDATION_PUBLIC_HEADERS)

require_text("src/test/CMakeLists.txt" "validation_library_install_shape_include_dir")
require_text("src/test/CMakeLists.txt" "target_include_directories(test_validation_library_header_self_containment")
forbid_text("src/test/CMakeLists.txt" "target_link_libraries(test_validation_library_header_self_containment")
require_text("src/test/CMakeLists.txt" "bitcoin_validation_installed_package")
require_text("src/test/bitcoin_validation_installed_package_consumer/CMakeLists.txt" "find_package(BitcoinValidation CONFIG REQUIRED)")
require_text("src/test/bitcoin_validation_installed_package_consumer/CMakeLists.txt" "Bitcoin::bitcoin_validation")
require_text("src/test/bitcoin_validation_installed_package_consumer/main.cpp" "verify_script")
require_text("src/test/CMakeLists.txt" "chain_graph_install_shape_include_dir")
require_text("src/test/CMakeLists.txt" "target_include_directories(test_bitcoin_chain_graph_header_self_containment")

foreach(rule IN LISTS BITCOIN_C_ABI_ACTIVE_CPP_CONCEPT_RULES)
  require_c_abi_cpp_concept_rule("${rule}")
endforeach()

foreach(rule IN LISTS BITCOIN_C_ABI_PENDING_CPP_CONCEPT_RULES)
  require_pending_c_abi_cpp_concept_rule("${rule}")
endforeach()

require_c_abi_functions_manifested()

fail_on_api_manifest_blockers()
