# Copyright (c) 2026-present The Bitcoin Core developers
# Distributed under the MIT software license, see the accompanying
# file COPYING or https://opensource.org/license/mit/.

include(FlagsSummary)

function(print_configure_summary)
  message("\n")
  message("Configure summary")
  message("=================")
  message("Executables:")
  message("  bitcoin ............................. ${BUILD_BITCOIN_BIN}")
  message("  bitcoind ............................ ${BUILD_DAEMON}")
  message("  bitcoin-node (multiprocess) ......... ${BUILD_DAEMON}")
  message("  bitcoin-cli ......................... ${BUILD_CLI}")
  message("  bitcoin-chainstate (experimental) ... ${BUILD_UTIL_CHAINSTATE}")
  message("  libbitcoinkernel (experimental) ..... ${BUILD_KERNEL_LIB}")
  message("  kernel-test (experimental) .......... ${BUILD_KERNEL_TEST}")
  message("Optional features:")
  message("  Embedded ASMap ...................... ${WITH_EMBEDDED_ASMAP}")
  message("  USDT tracing ........................ ${WITH_USDT}")
  message("Tests:")
  message("  test_bitcoin ........................ ${BUILD_TESTS}")
  message("  bench_bitcoin ....................... ${BUILD_BENCH}")
  message("  fuzz binary ......................... ${BUILD_FUZZ_BINARY}")
  message("")
  if(CMAKE_CROSSCOMPILING)
    set(cross_status "TRUE, for ${CMAKE_SYSTEM_NAME}, ${CMAKE_SYSTEM_PROCESSOR}")
  else()
    set(cross_status "FALSE")
  endif()
  message("Cross compiling ....................... ${cross_status}")
  message("C++ compiler .......................... ${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}, ${CMAKE_CXX_COMPILER}")
  flags_summary()
  message("Project hardening ..................... ${BITCOIN_ENABLE_HARDENING}")
  message("Treat compiler warnings as errors ..... ${CMAKE_COMPILE_WARNING_AS_ERROR}")
  message("\n")
  if(configure_warnings)
    message("  ******\n")
    foreach(warning IN LISTS configure_warnings)
      message(WARNING "${warning}")
    endforeach()
    message("  ******\n")
    message(AUTHOR_WARNING "Warnings have been encountered!")
  endif()
endfunction()
