name: 'Restore Caches'
description: 'Restore ccache, SDK, and previous releases caches'
runs:
  using: 'composite'
  steps:
    - name: Restore Ccache cache
      id: ccache-cache
      uses: cirruslabs/cache/restore@v5
      with:
        path: ${{ env.CCACHE_DIR }}
        key: ccache-${{ env.CONTAINER_NAME }}-${{ github.run_id }}
        restore-keys: |
          ccache-${{ env.CONTAINER_NAME }}-

    - name: Restore SDK cache
      id: sdk-cache
      uses: cirruslabs/cache/restore@v5
      with:
        path: ${{ env.SDK_CACHE_DIR }}
        key: sdk-cache-${{ env.CONTAINER_NAME }}-${{ env.SDK_CACHE_HASH }}
        restore-keys: |
          sdk-cache-${{ env.CONTAINER_NAME }}-

    - name: Restore previous releases cache
      id: previous-releases
      uses: cirruslabs/cache/restore@v5
      with:
        path: ${{ env.PREVIOUS_RELEASES_DIR }}
        key: previous-releases-${{ env.CONTAINER_NAME }}-${{ env.PREVIOUS_RELEASES_HASH }}
        restore-keys: |
          previous-releases-${{ env.CONTAINER_NAME }}-

    - name: export cache hits
      shell: bash
      run: |
        echo "sdk-cache-hit=${{ steps.sdk-cache.outputs.cache-hit }}" >> $GITHUB_ENV
        echo "previous-releases-cache-hit=${{ steps.previous-releases.outputs.cache-hit }}" >> $GITHUB_ENV
